FROM ubuntu:18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
    ca-certificates \
    build-essential \
    git \
    python3.7 \
    python3-pip
    
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install tensorflow
RUN pip3 install keras

WORKDIR /app

ENTRYPOINT ["python3"]
CMD ["AI-app.py"]
