trigger:
- master

pool: '$(agent_pool_name)'

variables:
  imageName: '$(ID_docker_hub)/ai-camera'
  dockerHub: '$(docker_service_connection)'
  tag: 'latest'

steps:

- task: Docker@2
  inputs:
    command: login
    containerRegistry: $(dockerHub)

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    containerRegistry: $(dockerHub)
    command: build
    Dockerfile: Dockerfile/Dockerfile_x86_ARM
    tags: $(tag)