trigger:
- master

pool: 'VM Agent'

variables:
  imageName: '$(ID_docker_hub)/ai-camera-VM-simulation'
  dockerHub: 'ai-docker'
  tag: 'latest'

steps:

- task: Docker@2
  inputs:
    command: login
    containerRegistry: $(dockerHub)

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    containerRegistry: $(dockerHub)
    command: build
    Dockerfile: Dockerfile_x86_ARM
    tags: $(tag)

- task: Docker@1
  displayName: 'Run an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: $(dockerHub)
    command: 'Run an image'
    imageName: $(imageName)
    runInBackground: false

- task: Docker@2
  displayName: Push image
  inputs:
    repository: $(imageName)
    containerRegistry: $(dockerHub)
    command: push
    tags: $(tag)