FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
    ca-certificates \
    build-essential \
    git \
    python3.7 \
    python3-pip

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV TF_FORCE_GPU_ALLOW_GROWTH true

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install tensorflow-gpu
RUN pip3 install keras
RUN pip3 install matplotlib
RUN pip3 install sklearn
RUN pip3 install Pillow
RUN pip3 install imutils

RUN apt-get install -y software-properties-common
RUN add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
RUN apt update

RUN apt-get install -y build-essential cmake pkg-config \
                       libjpeg-dev libtiff5-dev libjasper-dev libpng-dev \
                       libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
                       libxvidcore-dev libx264-dev \
                       libfontconfig1-dev libcairo2-dev \
                       libgdk-pixbuf2.0-dev libpango1.0-dev \
                       libgtk2.0-dev libgtk-3-dev \
                       libfontconfig1-dev libcairo2-dev\
                       libgdk-pixbuf2.0-dev libpango1.0-dev \
                       libgtk2.0-dev libgtk-3-dev \
                       libatlas-base-dev gfortran \
                       libhdf5-dev libhdf5-serial-dev \
                       libqtgui4 libqtwebkit4 libqt4-test python3-pyqt5 \
                       libilmbase-dev libopenexr-dev ibgstreamer1.0-dev \
                       libwebp6 libtiff5 libjasper1 libilmbase12 libopenexr22 \
                       libgstreamer1.0-0 libavcodec57 libswscale4 \
                       libqtcore4 libavformat57

# Install OpenCV
RUN pip3 install opencv-python
RUN pip3 install opencv-contrib-python


COPY ./AI_app/Model /app

WORKDIR /app

ENTRYPOINT ["python3"]
CMD ["train.py"]

